generatorName: 'java'
groupId: 'blog.openapi'
artifactId: 'client'
apiPackage: 'blog.openapi.client.rest'
modelPackage: 'blog.openapi.client.rest.dto'
artifactVersion: '1.0.2'
library: 'resteasy'
#inputSpec: 'latestopenapi.json'
inputSpec: 'openapi.yaml'
outputDir: 'client'
java8: 'true'
